stages:
  - build
  - utest

build:
  stage: build

  image: espressif/idf

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - idf.py build

utest:
  stage: utest

  image: gitlab.appliedlogix.com:4567/mn8-energy/light-controller-firmware

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - echo $(pwd)
    - cd main/gtest
    - cmake .
    - cmake --build .
    - ./led-test

