stages:
  - build
  - utest
  - publish

variables:
  ZIPPED_FW_FILE: MN8-*.zip

build:
  stage: build

  image: espressif/idf

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - idf.py build
    - ./utils/make_build_zip.sh

  artifacts:
    paths: 
      - ${ZIPPED_FW_FILE}

utest:
  stage: utest

  image: gitlab.appliedlogix.com:4567/mn8-energy/light-controller-firmware

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - echo $(pwd)
    - cd main/gtest
    - cmake .
    - cmake --build .
    - ./led-test

publish:
  stage: publish
  
  image: alpine:latest

  before_script:
    - apk update
    - apk add curl
  
  script:
    - 'package=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${CI_COMMIT_REF_NAME}-$(date +%y%m%d-%H%M%S)'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${ZIPPED_FW_FILE} "${package}/"'

  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
