#pragma once

#define VERSION_MAJOR 2
#define VERSION_MINOR 8
#define VERSION_PATCH 5
#define VERSION_ENV   LOCAL



#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define VERSION_STRING STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH)
